# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1405e1a01d7004977a6de453414863ec07f1549101a5dab7af70c8d09f820dfcb9a9cd4ee6384530cdac1d218102a13b75582e0ecd2c0986f90a46c9ff602e78

test:
  secret_key_base: 7176638ddb20b09d77b6f5de67f25fef6f3ba475c5c695ecdee941a7138a214c457898d8fc8099c406237d3218d864278138a8883bea1491d54bf12f89347ea7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
